version: '3'

services:
  sentiment-app:
    container_name: sentiment-app
    build: .
    depends_on:
      - redis
      - mongo
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=batch-db
      - MONGO_COLLECTION_NAME=batch-results
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
    ports:
      - '5000:5000'
      - '5555:5555'
    restart: always

  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    expose:
      - 6379
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
    ports:
      - '8081:8081'

networks:
  default:
    name: sentiment-net
