version: '3'

services:
  sentiment-app:
    container_name: sentiment-app
    build: .
    depends_on:
      - redis
      - mongo
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017/
      - MONGO_DB_NAME=batch-db
      - MONGO_COLLECTION_NAME=batch-results
    ports:
      - '5001:5000'
      - '5002:5555'
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    expose:
      - 6379
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'

networks:
  default:
    name: sentiment-net
